apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: components
  namespace: openshift-gitops
spec:
  generators:
    - list:
      elements:
      - name: instance
        source:
          repoURL: https://github.com/redhat-cop/gitops-catalog.git
          targetRevision: HEAD
          path: external-secrets-operator/instance/overlays/stable
          # Other source options
      - name: sub
        source:
          repoURL: https://github.com/redhat-cop/gitops-catalog.git
          targetRevision: HEAD
          path: external-secrets-operator/operator/overlays/stable
    - clusterDecisionResource:
        configMapRef: acm-placement # (1)
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: spokes-gitops-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: eso-operator-{{name}} # (2)
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}' 
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        namespace: spokes
        server: "{{server}}" # (3)
      syncPolicy:
        automated:
          selfHeal: false
        syncOptions:
          - CreateNamespace=true # (4)