apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: domain-service
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement # (1)
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: spokes-gitops-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: domain-service-{{name}} # (2)
    spec:
      project: default
      source:
        repoURL: https://gitlab.consulting.redhat.com/sforeman/innovative-solutions.git
        targetRevision: HEAD
        path: services/domain/overlays/dev
      destination:
        namespace: tailwinds-domain
        server: "{{server}}" # (3)
      syncPolicy:
        automated:
          selfHeal: false
        syncOptions:
          - CreateNamespace=true # (4)
