apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eso-operator
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement # (1)
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: spokes-gitops-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: eso-operator-{{name}} # (2)
    spec:
      project: default
      source:
        repoURL: https://github.com/parthghetia-rh/spoke-cluster-config.git
        targetRevision: main
        path: components
      destination:
        namespace: spokes
        server: "{{server}}" # (3)
      syncPolicy:
        automated:
          selfHeal: false
        syncOptions:
          - CreateNamespace=true # (4)