apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: spokes-gitops-placement
  namespace: weaviate
spec:
  clusterSets:
    - spokes
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - test
                - prod
